## List

In [ ]:
# membuat list
hewan = ["sapi", "kuda", "ayam", "kucing", "kambing"]
print(hewan)

['sapi', 'kuda', 'ayam', 'kucing', 'kambing']


In [ ]:
hewan.insert(4, "kudanil")
print(hewan)

['sapi', 'kuda', 'ayam', 'kucing', 'kudanil', 'kambing']


In [ ]:
hewan.remove("kudanil")
print(hewan)

['sapi', 'kuda', 'ayam', 'kucing', 'kambing']


In [ ]:
hewan.extend(["bebek", "kalkun", "beo"])
print(hewan)

['sapi', 'kuda', 'ayam', 'kucing', 'kambing', 'bebek', 'kalkun', 'beo']


In [ ]:
# mengakses
print(hewan[1])
print(hewan[2:5])

kuda
['ayam', 'kucing', 'kambing']


In [ ]:
# mengganti
hewan[1] = "gajah"
print(hewan)

['sapi', 'gajah', 'ayam', 'kucing', 'kambing', 'bebek', 'kalkun', 'beo']


In [ ]:
# mencari panjang
print(len(hewan))

8


## Tuple

In [ ]:
# membuat tuple
hewan = ("sapi", "kuda", "ayam", "kucing", "kambing")
print(hewan)

('sapi', 'kuda', 'ayam', 'kucing', 'kambing')


In [ ]:
# mengakses
print(hewan[1])
print(hewan[-1])
print(hewan[:5])

kuda
kambing
('sapi', 'kuda', 'ayam', 'kucing', 'kambing')


In [ ]:
# mengubah nilai
hewan = list(hewan)
hewan[1] = "gajah"
hewan = tuple(hewan)
print(hewan)

TypeError: 'tuple' object is not callable

In [ ]:
# panjang
print(len(hewan))

5


## Set

In [ ]:
# membuat set
hewan = {"sapi", "kuda", "ayam", "kucing", "ikan"}
print(hewan)

{'ayam', 'kuda', 'sapi', 'kucing', 'ikan'}


In [ ]:
# mengakses yang salah
print(hewan[1])

TypeError: 'set' object is not subscriptable

In [ ]:
# mengakses yang benar
for x in hewan :
  print(x)

ayam
kuda
sapi
kucing
ikan


In [ ]:
# atau
if "sapi" in hewan :
  print("ada sapi")
else :
  print("gaada")

ada sapi


## Dictionary

In [ ]:
# membuat dictionary
spesifikasi = {"merk" : "Infinix", "jenis" : "laptop","processor" : "intel_i3"}
print(spesifikasi)

{'merk': 'Infinix', 'jenis': 'laptop', 'processor': 'intel_i3'}


In [ ]:
# mengakses
x = spesifikasi["jenis"]
print(x)

print(spesifikasi.get("jenis"))

laptop
laptop


In [ ]:
# mengubah
spesifikasi["jenis"] = "Smartphone"
print(spesifikasi)

{'merk': 'Infinix', 'jenis': 'Smartphone', 'processor': 'intel_i3'}


In [ ]:
# panjang
print(len(spesifikasi))

3


## Array

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second,

In [ ]:
a = [1,2,3]
a.sort()
print(a)

[1, 2, 3]


In [ ]:
# membuat array 1 dimensi
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
print(a[1])

2


In [ ]:
#membuat array 2 dimensi
b = np.full((2,3), [[1,2,0],[3,4,5]])
print(b)

[[1 2 0]
 [3 4 5]]


In [ ]:
print(b[:2,1])

[2 4]


In [ ]:
#mencari jumlah dimensi
a.ndim

1

In [ ]:
#mencari ukuran
b.shape

(2, 3)

In [ ]:
c = np.array([])
jumlah = int(input("masukkan jumlah : "))
for i in range(jumlah) :
  x = int(input("masukkan angka ke - {} : ".format(i+1)))
  c = np.append(c,x)
print(c)
total = np.sum(c)
print(total)
print(total/len(c))

masukkan jumlah : 3
masukkan angka ke - 1 : 12
masukkan angka ke - 2 : 13
masukkan angka ke - 3 : 14
[12. 13. 14.]
39.0
13.0


In [ ]:
import numpy as np
total=int(input())
list=[]
for i in range (total):
  angka=int(input())
  list.append(angka)
x=np.array(list)
sorting=np.sort(x)
print(list)
print(sorting)

5
3
6
2
7
1
[3, 6, 2, 7, 1]
[1 2 3 6 7]


# Praktikum

## List

In [ ]:
list = [3, 6, 13, 10, 19, 45, 100, 120, 150]
print("list[2]:", list[2]) #Contoh akses nilai list dalam Python

list[2]: 13


In [ ]:
list.append(23) #Contoh update nilai list dalam Python
list.insert(4, 17)
print("Data List Setelah di Update: ", list)

Data List Setelah di Update:  [3, 6, 13, 10, 17, 19, 45, 100, 120, 150, 23]


In [ ]:
del list[1] #Contoh menghapus nilai list dalam Python
print("Data List: ", list )
list.remove(10)
print("Data List Baru: ", list)

Data List:  [3, 13, 10, 17, 19, 45, 100, 120, 150, 23]
Data List Baru:  [3, 13, 17, 19, 45, 100, 120, 150, 23]


In [ ]:
list.clear() #Contoh menghapus semua nilai list dalam Python
print("Data List Baru: ", list)

Data List Baru:  []


## Tuple

In [ ]:
list = (3, 6, 13, 10, 19, 45, 100, 120, 150)
list1=len(list)
print('List: ', list)
print('Panjang List: ', list1)

List:  (3, 6, 13, 10, 19, 45, 100, 120, 150)
Panjang List:  9


## Dictionary

In [ ]:
A = {"Andrian":"A1", "Vancy":"A2", "Dewi":"A3"}
p = A.keys()
print(p)

dict_keys(['Andrian', 'Vancy', 'Dewi'])


In [ ]:
type(p)

dict_keys

In [ ]:
l = tuple(A.keys())
print(l)

('Andrian', 'Vancy', 'Dewi')


In [ ]:
v= A.values()
print(v)

dict_values(['A1', 'A2', 'A3'])


In [ ]:
i=A.items()
print(i)

dict_items([('Andrian', 'A1'), ('Vancy', 'A2'), ('Dewi', 'A3')])


In [ ]:
g=A.get("Dewi")
print(g)

A3


In [ ]:
g1 = A.get("Fitri","NO ENTRY")
print(g1)

NO ENTRY


In [ ]:
help(dict.get)

Help on method_descriptor:

get(self, key, default=None, /)
    Return the value for key if key is in the dictionary, else default.



In [ ]:
a = input("Masukkan list : ").split(",")
for i in range(len(a)) :
  a[i] = a[i].lower()
cari = input("Masukkan yang ingin dicari : ")
cari = cari.lower()
if cari in a :
  print(f"dia merupakan anggota list ke-{a.index(cari)+1}")
else :
  print("gaada")

Masukkan list : c,b,d
Masukkan yang ingin dicari : B
dia merupakan anggota list ke-2


In [ ]:
nama_buah = tuple(input("Masukkan nama buah (pisahkan dengan koma): ").split(','))

jumlah_huruf = tuple(len(buah) for buah in nama_buah)

buah_terpanjang = nama_buah[jumlah_huruf.index(min(jumlah_huruf))]

print("Tuple nama buah:", nama_buah)
print("Tuple jumlah huruf:", jumlah_huruf)
print("Buah dengan jumlah huruf terbanyak:", buah_terpanjang)


Masukkan nama buah (pisahkan dengan koma): Anggur,Apel,Manggis,Pepaya
Tuple nama buah: ('Anggur', 'Apel', 'Manggis', 'Pepaya')
Tuple jumlah huruf: (6, 4, 7, 6)
Buah dengan jumlah huruf terbanyak: Apel


In [ ]:
data_siswa = {
    "Andi": 80,
    "Budi": 90,
    "Cindy": 100,
    "Dika": 70
}
rata_matematika = sum(data_siswa.values()) / len(data_siswa)
a = max(data_siswa.values())
for nama, nilai in data_siswa.items() :
  if nilai == a :
    siswa_terbaik_matematika = nama

print("Rata-rata nilai matematika:", rata_matematika)
print("Siswa dengan nilai matematika tertinggi:", siswa_terbaik_matematika)


Rata-rata nilai matematika: 85.0
Siswa dengan nilai matematika tertinggi: Cindy


In [ ]:
nama_buah = ("Leci","Blackcurret","apel")
for i in nama_buah:
  if i:
    panjang_terkecil = min(nama_buah, key = len)
    print(f"panjang buah terkecil adalah {panjang_terkecil}")
    print(f"panjang : {len(panjang_terkecil)}")
  break

panjang buah terkecil adalah Leci
panjang : 4
