In [ ]:
#Contoh penulisan list dalam Python
list1 = [1, "melati", "putih", 20]
list2 = ["lari marathon", "Surabaya", 2021]

In [1]:
list = [3, 6, 13, 10, 19, 45, 100, 120, 150]
print("list[2]: ", list[2]) #Contoh akses nilai list dalam Python
list.append(23) #Contoh update nilai list dalam Python
list.insert(4, 17)
print("Data List Setelah di Update: ", list)
del list[1] #Contoh menghapus nilai list dalam Python
print("Data List: ", list )
list.remove(10)
print("Data List Baru: ", list)
list.clear() #Contoh menghapus semua nilai list dalam Python
print("Data List Baru:" , list)

list[2]:  13
Data List Setelah di Update:  [3, 6, 13, 10, 17, 19, 45, 100, 120, 150, 23]
Data List:  [3, 13, 10, 17, 19, 45, 100, 120, 150, 23]
Data List Baru:  [3, 13, 17, 19, 45, 100, 120, 150, 23]
Data List Baru: []


In [1]:
list = (3, 6, 13, 10, 19, 45, 100, 120, 150)
list1=len(list)
print('List: ', list)
print('Panjang List: ', list1)

List:  (3, 6, 13, 10, 19, 45, 100, 120, 150)
Panjang List:  9


In [1]:
a= int(input("masukkan batas list : "))
list = []
for i in range (a):
    b = int(input(f"Masukkan angka ke - {i}"))
    list.append(b)
print(list)

ganjil = []
genap = []
for angka in list:
    if angka%2 == 0:
        genap.append(angka)
    elif angka%2 == 1:
        ganjil.append(angka)

print(f"list genap : {genap}")
print(f"list ganjil : {ganjil}")
hasil = sum(ganjil)
print(f"jumlah ganjil {hasil}")

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list genap : [2, 4, 6, 8, 10]
list ganjil : [1, 3, 5, 7, 9]
jumlah ganjil 25


In [3]:
buah = "Anggur, Apel, Semangka"
len(buah.split(",")) 

3

In [17]:
buah = ("Anggur", "Apel", "Semangka")
jumlah = []
for i in buah:
    jumlah.append(len(i))
print(jumlah)



[6, 4, 8]


In [5]:
import numpy as np
print(np.zeros(4))
print(np.ones(2))
print(np.empty(4))
print(np.full(4,5))
print(np.eye(4))
print(np.random.randint(2,10,size=(3,3)))

[0. 0. 0. 0.]
[1. 1.]
[0. 0. 0. 0.]
[5 5 5 5]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[8 6 2]
 [9 2 3]
 [6 7 8]]
